---
- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    append: yes
  loop: "{{ users }}"

- name: Create .ssh directory if it doesn't exist
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH key to authorized_keys file
  lineinfile:
    path: "~/.ssh/authorized_keys"
    line: "{{ item.ssh_key }}"
    create: yes
  loop:
    - { ssh_key: "ssh-rsa AAAAB3...your_ssh_key_here" }
