---
- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    append: yes
  
- name: Make sure ssh exists
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"

- name: Add SSH key to authorized_keys file
  lineinfile:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    line: "{{ item.ssh_key }}"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
