---
- name: Deploy application
  hosts: cluster_hosts
  become: yes
  tasks:
    - include_vars: vars/app-vars.yml

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Ensure Git is installed
      ansible.builtin.apt:
        name: git
        state: present

    - name: Create app directory
      file:
        path: "/app"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Download .env.j2 template from a URL
      get_url:
        url: "{{ env_file_url }}"
        dest: "./.env.j2"
        headers:
          Authorization: "token {{ git_token }}"
          Accept: application/vnd.github.v3.raw
      delegate_to: localhost

    - name: Clone the repository
      git:
        repo: "https://{{ git_token }}@github.com/R0kkxSynetique/RIA2-FULL-COMPOSE.git"
        dest: "/app"

    - name: Generate .env file
      template:
        src: ./.env.j2
        dest: /app/.env

    - name: Start Docker Compose
      command: docker compose -f docker-compose.prod.yml up -d --build
      args:
        chdir: /app
