---
- name: Setup docker host
  become: yes
  hosts: cluster_hosts
  tasks:
    - name: Create docker's user group
      group:
        name: docker
        state: present

    - name: Install docker
      include_role:
        name: geerlingguy.docker