---
- name: Setup newly created instances
  become: yes
  hosts: all
  tasks:
    - name: Setting up NAT server
      block:
        - include_vars: vars/clients.yml
        - include_tasks: tasks/nat.yml
        - include_tasks: tasks/vhosts.yml
        - include_tasks: tasks/clients_access.yml
          loop: "{{ clients }}"
      when: "'nat_servers' in group_names"

      
    - name: Setting up the cluster servers
      block:
        - include_tasks: tasks/docker.yml
        - include_tasks: tasks/app.yml
      when: "'cluster_hosts' in group_names"